// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrUpdateSwipe(ctx context.Context, arg CreateOrUpdateSwipeParams) (Swipe, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUser(ctx context.Context, username string) (User, error)
	ListSwipableProfiles(ctx context.Context, arg ListSwipableProfilesParams) ([]ListSwipableProfilesRow, error)
}

var _ Querier = (*Queries)(nil)
